### PR TITLE
Add OpenGL 4.6 support.

### PR DESCRIPTION
**Pull request by kjozic**

### CODE REVIEW

**Comment by shurcooL** [comment]
Thanks for doing this.

How did you make this change? How can I reproduce it and verify these changes are correct?

**Comment by kjozic** [comment]
The procedure is straightforward:
1. Fork both gl and glow repositories
2. Create a new branch in each repository
3. Download the files mentioned in the issue "OpenGL 4.6 support" (gl repo) and put them into glow/xml/spec folder
4. Switch to gl folder and run following commands:
```
glow generate -out=./v4.6-core/gl/ -api=gl -version=4.6 -profile=core -xml=../glow/xml/
glow generate -out=./v4.6-compatibility/gl/ -api=gl -version=4.6 -profile=compatibility -xml=../glow/xml/
```
5. Commit the changes and create the pull requests
6. Repo gl uses Travis CI for continuous integration; glow does not use CI (it just checks for the merge conflicts)

**Comment by shurcooL** [comment]
Thanks.

After looking more into it, I found there's a command in `glow` to download updated XML files:

```
$ glow
Usage: glow command [arguments]
Commands:
  download  Downloads specification and documentation XML files
  generate  Generates bindings
Use glow <command> -help for a detailed command description
```

It also downloads new files in [`xml/doc`](https://github.com/go-gl/glow/tree/master/xml/doc) directory.

```
$ glow download
2017/11/09 19:51:41 Downloading https://cvs.khronos.org/svn/repos/ogl/trunk/doc/registry/public/api/wgl.xml
2017/11/09 19:51:41 Downloading https://cvs.khronos.org/svn/repos/ogl/trunk/doc/registry/public/api/gl.xml
2017/11/09 19:51:41 Downloading https://cvs.khronos.org/svn/repos/ogl/trunk/doc/registry/public/api/egl.xml
2017/11/09 19:51:41 Downloading https://cvs.khronos.org/svn/repos/ogl/trunk/doc/registry/public/api/glx.xml
2017/11/09 19:51:44 Downloading https://cvs.khronos.org/svn/repos/ogl/trunk/ecosystem/public/sdk/docs/man2/glActiveTexture.xml
2017/11/09 19:51:44 Downloading https://cvs.khronos.org/svn/repos/ogl/trunk/ecosystem/public/sdk/docs/man2/glBindBuffer.xml
2017/11/09 19:51:44 Downloading https://cvs.khronos.org/svn/repos/ogl/trunk/ecosystem/public/sdk/docs/man2/glBeginQuery.xml
2017/11/09 19:51:44 Downloading https://cvs.khronos.org/svn/repos/ogl/trunk/ecosystem/public/sdk/docs/man2/glAlphaFunc.xml
2017/11/09 19:51:44 Downloading https://cvs.khronos.org/svn/repos/ogl/trunk/ecosystem/public/sdk/docs/man2/glAreTexturesResident.xml
2017/11/09 19:51:44 Downloading https://cvs.khronos.org/svn/repos/ogl/trunk/ecosystem/public/sdk/docs/man2/glArrayElement.xml
2017/11/09 19:51:44 Downloading https://cvs.khronos.org/svn/repos/ogl/trunk/ecosystem/public/sdk/docs/man2/glAttachShader.xml
2017/11/09 19:51:44 Downloading https://cvs.khronos.org/svn/repos/ogl/trunk/ecosystem/public/sdk/docs/man2/glAccum.xml
2017/11/09 19:51:44 Downloading https://cvs.khronos.org/svn/repos/ogl/trunk/ecosystem/public/sdk/docs/man2/glBegin.xml
...
```

I'll push a commit to apply that change.

**Comment by shurcooL** [comment]
Looks like I jumped too quickly with this. It seems the latest XML files from that cvs source do not yet contain definitions for OpenGL 4.6. That's why you used a difference source in https://github.com/go-gl/gl/issues/88#issuecomment-342542558.

So, this PR, as merged, is not sufficient to add OpenGL 4.6 support.

Any ideas why https://raw.githubusercontent.com/KhronosGroup/OpenGL-Registry/master/xml/gl.xml contains 4.6 but not https://cvs.khronos.org/svn/repos/ogl/trunk/doc/registry/public/api/gl.xml?

**Comment by shurcooL** [comment]
I'm going to revert what I merged for now, because the commit message is too misleading. That change updates to latest XML from our cvs source, but it doesn't add OpenGL 4.6 support. We should figure out what to do. /cc @errcw

I don't want to regenerate `gl` repo, and I don't want it to be out of date with `glow`, so reverting is the best action for now. Re-apply this will be trivial once we figure out what to do.

**Pull request merged**
